name: Test
on:
  push:
    branches-ignore:
      - 'none'
jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Generate gradle wrapper
        run: gradle wrapper
      - name: Run test
        run: ./gradlew clean test
